name: Auto

on:
  schedule:
    - cron: "10 5 * * *"  # JST 14:10 → UTC 5:10
  workflow_dispatch:

env:
  DIFY_TOKENS: ${{ secrets.DIFY_TOKENS }}
  DIFY_BASE_URL: "http://172.16.6.241/v1/workflows/run"  # 社内DifyのAPIエンドポイント
  DIFY_WORKFLOW_ID: "hpayW0cZj8unBxVr"

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Dify Workflow
        run: |
          curl -X POST "$DIFY_BASE_URL" \
          -H "Authorization: Bearer $DIFY_TOKENS" \
          -H "Content-Type: application/json" \
          -d '{
            "workflow_id": "'"$DIFY_WORKFLOW_ID"'",
            "inputs": {
              "date": "'$(date +%Y-%m-%d)'"
            },
            "response_mode": "blocking"
          }'
``
