name: Auto

on:
  schedule:
    - cron: "10 5 * * *"
  workflow_dispatch:

env:
  DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
  DIFY_API_URL: ${{ secrets.DIFY_API_URL }}
  DIFY_WORKFLOW_ID: ${{ secrets.DIFY_WORKFLOW_ID }}

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Dify Workflow
        run: |
          curl -X POST "$DIFY_API_URL" \
          -H "Authorization: Bearer $DIFY_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "workflow_id": "'"$DIFY_WORKFLOW_ID"'",
            "inputs": {
              "date": "'$(date +%Y-%m-%d)'"
            },
            "response_mode": "blocking"
          }'
